### PR TITLE
:zap: chore: Replaced fetching gitmojis.json for dependency

### LINKED ISSUE #128: 无法获取gitmojis.json文件问题——解决方案提议
您好，ccommitlint-plugin-gitmoji使用时 Failed to fetch gitmoji JSON，看了您的文档解决方法需要自己下载gitmojis.json文件放node_modules里，我觉得这样不太合理，这样我和我的搭档一起写代码我们都需要下载一份这个文件放本地node_modules。我觉得这个文件您可以下载放在您的包里，如果Failed to fetch gitmoji JSON就引用您项目内的gitmojis.json文件，这样使用起来更友好些，您觉得呢？

### PR DESCRIPTION
**Pull request by bryanjtc**
I replaced all the code and tests that were used to fetch the file `gitmojis.json` for the dependency `gitmojis`. It's just easier this way and it doesn't throw errors.
Fixes #128 #415

### CODE REVIEW

**Comment by bryanjtc** [comment]
@arvinxx Can you check this?

**Comment by bryanjtc** [comment]
Any update on this? @arvinxx

**Comment by rdbisme** [comment]
I also think this should be merged.

**Comment by arvinxx** [comment]
Thanks for your great work. I'll merge it~

**Pull request merged**
